# fly.toml app configuration file generated for wfm-input on 2024-12-15T09:28:59+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wfm-input'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
